notifications:
  email: false

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3

# script, expressed as an array, is necessary for 'bundle exec coveralls push' to work locally
script:
  - bundle exec rake

cache: bundler

before_install:
  - gem install bundler # the default version of bundler for ruby 2.1 is out of date.
