notifications:
  email: false

rvm:
  - 2.1.2
  - 2.2.4
  - 2.3.1
  - 2.4.2
  - 2.5.3

# script, expressed as an array, is necessary for 'bundle exec coveralls push' to work locally
script:
  - bundle exec rake

cache: bundler

before_install:
  - gem install bundler # the default version of bundler for ruby 2.1 is out of date.
